"""Render the ontology as an LLM skill: ``SKILL.md`` plus one reference file per branch.

Nobody edits the skill by hand. It is rendered from the ontology tree (on every ontology
commit in CI, see ``verdy ontology render --check``), so it can't drift:

``SKILL.md``
    Naming conventions, unit rules, how to write distributions and grounding, the top-level
    branches with one-line descriptions, and worked examples.
``references/<branch>.md``
    The full subtree of one top-level branch, loaded only when extraction touches it.

ODD authoring sends ``SKILL.md`` with the extraction request and the references of the
branches its misses fall in with the miss-authoring request, and records
:func:`skill_sha256` in the ODD's ``metadata.authoring``, so the evidence report pins
exactly what the LLM was told.
"""
from __future__ import annotations

import hashlib
from collections.abc import Iterable
from pathlib import Path

from verdy.odd.ontology import Node, Ontology, OntologyEntry, default_label

SKILL_FILE = "SKILL.md"
REFERENCES_DIR = "references"


def _header(onto: Ontology) -> str:
    return (f"<!-- Generated by `verdy ontology render` from {onto.ref} "
            f"(ontology sha256 {onto.sha256[:16]}). Do not edit: edit the ontology. -->")


def _fmt_range(e: OntologyEntry) -> str:
    if e.range is None:
        return ""
    lo, hi = (int(x) if float(x).is_integer() else x for x in e.range)
    return f"[{lo}, {hi}]"


def _leaf_line(e: OntologyEntry) -> str:
    facts = [e.type]
    if e.unit:
        facts.append(e.unit)
    if e.range is not None:
        facts.append(_fmt_range(e))
    if e.values:
        facts.append("values: " + ", ".join(map(str, e.values)))
    if e.distribution:
        facts.append(e.distribution)
    line = f"`{e.name}` ({'; '.join(facts)}): {e.description}"
    if e.synonyms:
        line += f" Aliases: {', '.join(e.synonyms)}."
    if e.grounding:
        line += " Grounding: " + ", ".join(f"{k}={v}" for k, v in e.grounding.items()) + "."
    if e.status != "approved":
        line += f" **[{e.status}]**"
    return line


def _group_line(n: Node) -> str:
    line = f"**{n.name}** ({n.label or default_label(n.name)}): {n.description}"
    if n.synonyms:
        line += f" Aliases: {', '.join(n.synonyms)}."
    if n.status != "approved":
        line += f" **[{n.status}]**"
    return line


def _tree_lines(onto: Ontology, name: str, depth: int) -> list[str]:
    out = []
    for child in onto.children(name):
        bullet = "  " * depth + "- "
        if isinstance(child, OntologyEntry):
            out.append(bullet + _leaf_line(child))
        else:
            out.append(bullet + _group_line(child))
            out.extend(_tree_lines(onto, child.name, depth + 1))
    return out


def render_reference(onto: Ontology, root: str) -> str:
    node = onto.node(root)
    lines = [
        _header(onto), "",
        f"# {node.label or default_label(root)} (`{root}`)", "",
        node.description, "",
        "Groups are in bold; leaves (ODD parameters) are in code font with type, unit, "
        "physical bounds and nominal distribution.", "",
    ]
    lines += _tree_lines(onto, root, 0)
    return "\n".join(lines) + "\n"


def _examples(onto: Ontology) -> list[OntologyEntry]:
    """Up to three leaves with aliases, from different branches, in file order."""
    picked: list[OntologyEntry] = []
    roots_seen: set[str] = set()
    for e in onto.entries:
        if e.synonyms and e.category not in roots_seen and e.status == "approved":
            picked.append(e)
            roots_seen.add(e.category)
        if len(picked) == 3:
            break
    return picked


def render_skill_md(onto: Ontology) -> str:
    units = sorted({e.unit for e in onto.entries if e.unit})
    lines = [
        "---",
        f"name: verdy-ontology-{onto.name}",
        f"description: Canonical ODD parameter names, units, ranges, distributions and "
        f"grounding from the {onto.name} parameter ontology ({onto.ref}). Use when extracting "
        "operating conditions from a description or drafting ODD parameters, to reuse "
        "existing names instead of inventing near-duplicates.",
        "---",
        _header(onto), "",
        f"# The {onto.name} parameter ontology", "",
        onto.description or "Canonical ODD parameters, as a tree.", "",
        f"{len(onto.entries)} parameters (leaves) in {len(onto.groups)} groups. Roots are the "
        "ODD categories; a parameter's category is its root.", "",
        "## Naming conventions", "",
        "- Ids are snake_case and name the measured quantity, not the situation: `turbidity`, "
        "not `murky_water`; `current_speed`, not `strong_current`.",
        "- Reuse an existing leaf whenever it measures the same quantity, even if the wording "
        "or unit differs. Its aliases list the wordings already seen.",
        "- Don't create near-duplicates (`water_clarity` next to `turbidity`). If a quantity "
        "is new, say which group it belongs under.",
        "- Booleans are named for the condition that is true (`comms_loss`, `glare`).",
        "- Units go in `unit`, never in the id.", "",
        "## Units", "",
        "- Use SI or the unit the ontology already uses for that quantity. Units in this "
        "ontology: " + (", ".join(f"`{u}`" for u in units) or "none") + ".",
        "- A leaf's range is its physical bounds, in its unit. An ODD narrows the range to "
        "the conditions it covers; convert units before narrowing (knots to m/s, F to degC).",
        "- Fractions and probabilities are unitless in [0, 1].", "",
        "## Distributions", "",
        "The nominal frequency of each value in deployment:", "",
        "- Numeric: `uniform`, `normal(mu, sigma)`, `loguniform` (min > 0; for quantities "
        "spanning orders of magnitude), `triangular(mode)`, `beta(a, b)` (on the range).",
        "- Categorical: `uniform`, or `weights` aligned with `values`.",
        "- Boolean: `bernoulli(p)`, p = probability of true.",
        "- Omit the distribution when the description gives no basis; uniform is assumed.", "",
        "## Grounding", "",
        "- `sim`: the simulator parameter the value sets.",
        "- `runtime`: the on-robot signal that measures it (a topic or path), used by runtime "
        "monitors to check the robot stays inside the ODD.", "",
        "## Branches", "",
        "| Branch | Covers | Groups | Parameters | Reference |",
        "| --- | --- | --- | --- | --- |",
    ]
    for root in onto.roots:
        sub = onto.subtree(root.name)
        groups = [n.name for n in sub[1:] if not isinstance(n, OntologyEntry)]
        leaves = [n for n in sub if isinstance(n, OntologyEntry)]
        lines.append(f"| `{root.name}` | {root.description} | "
                     f"{', '.join(f'`{g}`' for g in groups) or '-'} | {len(leaves)} | "
                     f"[{REFERENCES_DIR}/{root.name}.md]({REFERENCES_DIR}/{root.name}.md) |")
    lines += ["", "Load a branch's reference file before drafting a parameter in it.", "",
              "## Worked examples", ""]
    for i, e in enumerate(_examples(onto), 1):
        phrase = e.synonyms[0]
        lines += [
            f"{i}. \"{phrase}\" is `{e.name}` ({' → '.join(onto.path(e.name))}):", "",
            "   ```yaml",
            f"   - name: {e.name}",
            f"     category: {e.category}",
            f"     type: {e.type}",
        ]
        if e.unit:
            lines.append(f"     unit: {e.unit}")
        if e.range is not None:
            lines.append(f"     range: {_fmt_range(e)}   # narrow to what the description says")
        if e.values:
            lines.append(f"     values: [{', '.join(map(str, e.values[:3]))}]   # the subset meant")
        if e.distribution:
            lines.append(f"     distribution: {e.distribution}")
        if e.grounding:
            lines.append("     grounding: {" + ", ".join(
                f"{k}: {v}" for k, v in e.grounding.items()) + "}")
        lines += ["   ```", ""]
    lines += [
        f"{len(_examples(onto)) + 1}. A quantity with no leaf (\"gap between jacket legs\"): "
        "don't force it onto the nearest leaf. Pick the group it belongs under (here `task`), "
        "and draft a new parameter with a snake_case id, a one-line definition, unit, "
        "physical bounds and aliases. It is proposed as a new ontology entry for a human to "
        "approve.", "",
    ]
    return "\n".join(lines)


def render_skill(onto: Ontology) -> dict[str, str]:
    """``{relative path: content}`` for the whole skill."""
    files = {SKILL_FILE: render_skill_md(onto)}
    for root in onto.roots:
        files[f"{REFERENCES_DIR}/{root.name}.md"] = render_reference(onto, root.name)
    return files


def skill_sha256(files: dict[str, str]) -> str:
    h = hashlib.sha256()
    for path in sorted(files):
        h.update(path.encode() + b"\0" + files[path].encode() + b"\0")
    return h.hexdigest()


def skill_prompt(onto: Ontology, branches: Iterable[str] = ()) -> str:
    """SKILL.md (without front matter) plus the references of ``branches``, for a prompt."""
    files = render_skill(onto)
    body = files[SKILL_FILE].split("---\n", 2)[-1]
    parts = [body]
    for b in dict.fromkeys(branches):
        ref = files.get(f"{REFERENCES_DIR}/{b}.md")
        if ref:
            parts.append(ref)
    return "\n\n".join(parts)


def write_skill(onto: Ontology, out_dir: str | Path, *, check: bool = False) -> list[str]:
    """Write the rendered skill; return paths that changed (or, with ``check``, would).

    Stale reference files for branches that no longer exist are removed (or reported).
    """
    out = Path(out_dir)
    files = render_skill(onto)
    changed = []
    for rel, text in files.items():
        path = out / rel
        if not path.is_file() or path.read_text("utf-8") != text:
            changed.append(rel)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, "utf-8")
    ref_dir = out / REFERENCES_DIR
    if ref_dir.is_dir():
        for path in sorted(ref_dir.glob("*.md")):
            rel = f"{REFERENCES_DIR}/{path.name}"
            if rel not in files:
                changed.append(rel)
                if not check:
                    path.unlink()
    return changed
